### ISSUE TITLE
application/json in README but not supported

### ISSUE THREAD

**Issue by joachimvh** [rubensworks/rdf-serialize.js#2]
The README says `application/json` is one of the supported types, but when giving that content type to the serializer it errors with `Unrecognized media type: application/json`. So either the README should be updated, or ld+json should be generated when json is requested.

As comparison, the `rdf-parse` library does accept `application/json` as input. In that case it does error if you input `{}` whereas it doesn't error there if set the content type to `application/ld+json` so perhaps I'm missing something there.

For context: currently the CSS errors if you request an RDF resource with accept header `application/json` and how to solve that depends a bit on what this library does.

**Comment by rubensworks** [comment]
Hmm, I would say the README is wrong, and the erroring behaviour is correct then.
Because the JSON-LD spec makes `application/json` and `application/ld+json` have different meanings (the latter MUST have a separate context in order to interpret it as JSON-LD).

So I would propose updating the README.

What do you think?

**Comment by joachimvh** [comment]
Makes sense if there is this specific definition for it. The CSS will have to do some type conversion then.
